// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7yvUtNEWqxjVzkzrvJzmlX4Se3SLg6UI',
    appId: '1:989704330838:web:c74c63c530558170a925f7',
    messagingSenderId: '989704330838',
    projectId: 'groceryapp-flutter-cd7fe',
    authDomain: 'groceryapp-flutter-cd7fe.firebaseapp.com',
    storageBucket: 'groceryapp-flutter-cd7fe.appspot.com',
    measurementId: 'G-XGP4GPDXT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoEYzJmfJeqlwXaS2ESjVhTR9FRQbCIZw',
    appId: '1:989704330838:android:5d9ed39fdd00b9a4a925f7',
    messagingSenderId: '989704330838',
    projectId: 'groceryapp-flutter-cd7fe',
    storageBucket: 'groceryapp-flutter-cd7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVIZGMeOjROldbTsZeY7izknnfAfDPtds',
    appId: '1:989704330838:ios:1e0edcf91ceb548aa925f7',
    messagingSenderId: '989704330838',
    projectId: 'groceryapp-flutter-cd7fe',
    storageBucket: 'groceryapp-flutter-cd7fe.appspot.com',
    androidClientId: '989704330838-sa8lma8auu7ir9gsjf1q1rg39q5e0p9c.apps.googleusercontent.com',
    iosClientId: '989704330838-8u5ps85bqknfjeo6qdjrv1f129jggpj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVIZGMeOjROldbTsZeY7izknnfAfDPtds',
    appId: '1:989704330838:ios:1e0edcf91ceb548aa925f7',
    messagingSenderId: '989704330838',
    projectId: 'groceryapp-flutter-cd7fe',
    storageBucket: 'groceryapp-flutter-cd7fe.appspot.com',
    androidClientId: '989704330838-sa8lma8auu7ir9gsjf1q1rg39q5e0p9c.apps.googleusercontent.com',
    iosClientId: '989704330838-8u5ps85bqknfjeo6qdjrv1f129jggpj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdminPanel',
  );
}
